config/routes.rb
Rails.application.routes.draw do
  root 'teams#index'

  resources :teams, only: [:index, :new, :create] do
    resources :retrospectives do
      resources :demands do
        get 'update_status', on: :member
      end
      resources :doubts
      resources :positive_topics
      resources :negative_topics
    end

    resource :config, only: [:show]
  end

  resources :topics do
    member do
      post :like
      post :dislike
    end
  end
end

app/views/shared/_footer.html.erb
<footer class="ls-footer" role="contentinfo">
  <div class="ls-footer-info">
    <span class="last-access ls-ico-screen"><strong>Último acesso: </strong>99/99/9999 99:99:99</span>
    <p class="ls-copy-right">Copyright © Niceretro</p>
  </div>
</footer>

app/views/shared/_head.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">

<title>Niceretro</title>

<%= stylesheet_link_tag Locastyle.url + '/stylesheets/locastyle.css' %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= favicon_link_tag 'favicon.ico', rel: 'shortcut icon', type: 'image/x-icon' %>
<%= csrf_meta_tags %>

app/views/shared/_menu.html.erb
<aside class="ls-sidebar">

  <div class="ls-sidebar-inner">

    <nav class="ls-menu">
      <ul>
        <li>
          <%= link_to t('menu.teams'), root_path, class: 'ls-ico-users', title: t('menu.teams') %>
        </li>
        <li>
          <%= link_to t('menu.retrospectives'), team_retrospectives_path(current_team), class: 'ls-ico-calendar', title: t('menu.retrospectives') if current_team %>
        </li>
        <li>
          <%= link_to t('menu.create_retrospective'), new_team_retrospective_path(current_team), class: 'ls-ico-plus', title: t('menu.create_retrospective') if current_team %>
        </li>
        <li>
          <%= link_to t('menu.config'), team_config_path(current_team), class: 'ls-ico-cog', title: t('menu.config') if current_team %>
        </li>
      </ul>
    </nav>

  </div>

</aside>

app/views/shared/_pre_panel_menu.html.erb
<aside class="ls-sidebar">
  <div class="ls-sidebar-inner">
    <h1 class="ls-brand-name ls-ico-week"><%= link_to 'Niceretro', root_path %></h1>
    <nav class="ls-menu">
      <ul>
        <li>
          <%= link_to 'Adicionar Time', new_team_path, remote: true, class: 'ls-ico-plus' %>
        </li>
      </ul>
    </nav>
  </div>
</aside>

app/views/shared/_pre_panel_topbar.html.erb
<div class="ls-topbar ls-topbar-gray">

  <div class="ls-notification-topbar">

    <!-- <div class="ls-alerts-list">
      <a href="#" class="ls-ico-bell-o" data-counter="8" data-ls-module="topbarCurtain" data-target="#ls-notification-curtain"><span>Notificações</span></a>
      <a href="#" class="ls-ico-bullhorn" data-ls-module="topbarCurtain" data-target="#ls-help-curtain"><span>Ajuda</span></a>
      <a href="#" class="ls-ico-question" data-ls-module="topbarCurtain" data-target="#ls-feedback-curtain"><span>Sugestões</span></a>
    </div> -->

    <!-- <div data-ls-module="dropdown" class="ls-dropdown ls-user-account">
      <a href="#" class="ls-ico-user">
        <img src="assets/images/locastyle/avatar-example.jpg" alt="" />
        <span class="ls-name">João Kennedy</span>
        (johnkennedy)
      </a>

      <nav class="ls-dropdown-nav ls-user-menu">
        <ul>
          <li><a href="#">Meus dados</a></li>
          <li><a href="#">Sair</a></li>
         </ul>
      </nav>
    </div> -->
  </div>

  <span class="ls-show-sidebar ls-ico-menu"></span>
</div>

app/views/shared/_scripts.html.erb
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= javascript_include_tag Locastyle.url + '/javascripts/locastyle.js' %>
<%= javascript_include_tag 'http://ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.min.js' %>
<%= javascript_include_tag 'http://ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/additional-methods.min.js' %>

app/views/shared/_topbar.html.erb
<div class="ls-topbar">

  <div class="ls-notification-topbar">

    <!-- <div class="ls-alerts-list">
      <a href="#" class="ls-ico-bell-o" data-counter="8" data-ls-module="topbarCurtain" data-target="#ls-notification-curtain"><span>Notificações</span></a>
      <a href="#" class="ls-ico-bullhorn" data-ls-module="topbarCurtain" data-target="#ls-help-curtain"><span>Ajuda</span></a>
      <a href="#" class="ls-ico-question" data-ls-module="topbarCurtain" data-target="#ls-feedback-curtain"><span>Sugestões</span></a>
    </div> -->

    <!-- <div data-ls-module="dropdown" class="ls-dropdown ls-user-account">
      <a href="#" class="ls-ico-user">
        <img src="assets/images/locastyle/avatar-example.jpg" alt="" />
        <span class="ls-name">João Kennedy</span>
        (johnkennedy)
      </a>

      <nav class="ls-dropdown-nav ls-user-menu">
        <ul>
          <li><a href="#">Meus dados</a></li>
          <li><a href="#">Sair</a></li>
         </ul>
      </nav>
    </div> -->
  </div>

  <span class="ls-show-sidebar ls-ico-menu"></span>

  <h1 class="ls-brand-name">
    <%= link_to root_path(), class: 'ls-ico-week ls-v-align-middle' do %>
      <%= t('niceretro') %> / <%= current_team.name %>
    <% end %>
  </h1>
</div>