config/routes.rb
Rails.application.routes.draw do
  root 'teams#index'

  resources :teams, only: [:index, :new, :create] do
    resources :retrospectives do
      resources :demands do
        get 'update_status', on: :member
      end
      resources :doubts
      resources :positive_topics
      resources :negative_topics
    end

    resource :config, only: [:show]
  end

  resources :topics do
    member do
      post :like
      post :dislike
    end
  end
end

app/models/retrospective.rb
class Retrospective < ActiveRecord::Base
  belongs_to :team

  has_many :demands
  has_many :doubts, dependent: :destroy
  has_many :negative_topics, dependent: :destroy
  has_many :positive_topics, dependent: :destroy

  scope :next, -> { order(date: :desc).first }

  def is_enabled?
    self == team.retrospectives.next
  end
end

app/controllers/retrospectives_controller.rb
class RetrospectivesController < ApplicationController
  def index
    @retrospectives = Retrospective.where(team: current_team).order(date: :desc)
    @next_retrospective = Retrospective.where(team: current_team).next
  end

  def new
    @retrospective = RetrospectiveDecorator.new(Retrospective
                                                .new(team: current_team))
  end

  def create
    @retrospective = Retrospective.new(retrospectives_params.merge(team: current_team))

    if @retrospective.save
      redirect_to team_retrospectives_path(current_team)
    end
  end

  def edit
    @retrospective = RetrospectiveDecorator.new(current_team
                                                .retrospectives
                                                .find(params[:id]))
  end

  def update
    @retrospective = current_team.retrospectives.find(params[:id])
    if @retrospective.update_attributes(retrospectives_params)
      redirect_to team_retrospectives_path(current_team)
    else
      render :edit
    end
  end

  def destroy
    @retrospective = current_team.retrospectives.find(params[:id])
    @retrospective.destroy

    if @retrospective.destroyed?
      redirect_to team_retrospectives_path(current_team)
    end
  end

  def show
    @retrospective = current_team.retrospectives.find(params[:id])
    @latest_demands = current_team.demands.latest_demands(@retrospective)
    @is_enabled = @retrospective.is_enabled?
    demands
    doubts
    positive_topics
    negative_topics
  end

  private

  def demands
    @demands = @retrospective.demands.order(:id)
    @demand = Demand.new
  end

  def doubts
    @doubts = @retrospective.doubts.order(:id)
    @doubt = Doubt.new
  end

  def positive_topics
    @positive_topics = @retrospective.positive_topics.order(:id)
    @positive_topic = PositiveTopic.new
  end

  def negative_topics
    @negative_topics = @retrospective.negative_topics.order(:id)
    @negative_topic = NegativeTopic.new
  end

  def retrospectives_params
    params.require(:retrospective).permit(:title, :date, :room, :schedule)
  end
end

app/views/retrospectives/_form.html.erb
<div class="ls-box ls-board-box col-lg-6 col-md-8">
  <fieldset>
    <%= form_for [current_team, @retrospective], html: { class: 'ls-form row validate' } do |f| %>
      <label class="ls-label col-md-12">
        <b class="ls-label-text"><%= t('form.title') %>:</b>
        <%= f.text_field :title, required: true %>
      </label>
      <div class="col-md-4">
        <label class="ls-label">
          <b class="ls-label-text"><%= t('form.room') %>:</b>
          <%= f.number_field :room, required: true %>
        </label>
      </div>
      <div class="col-md-4">
        <label class="ls-label">
          <b class="ls-label-text"><%= t('form.date') %>:</b>
          <div class="ls-prefix-group">
            <%= f.text_field :date, class: 'datepicker', placeholder: 'dd/mm/aaaa', id: 'retrospective-date', value: (@retrospective.date.strftime(t('date.formats.default')) if @retrospective.date), required: true %>
            <a class="ls-label-text-prefix ls-ico-calendar" data-trigger-calendar="#retrospective-date" href="#"></a>
          </div>
        </label>
      </div>
      <div class="col-md-4">
        <label class="ls-label">
          <b class="ls-label-text"><%= t('form.schedule') %>:</b>
          <%= f.time_field :schedule, value: @retrospective.schedule, required: true %>
        </label>
      </div>
      <div class="col-md-12">
        <%= f.submit t('form.save'), class: 'ls-btn-primary ls-no-margin-left' %>
      </div>
    <% end %>
  </fieldset>
</div>

app/views/retrospectives/edit.html.erb
<h1 class="ls-title-intro ls-ico-plus"><%= t('title.edit_retrospective') %></h1>

<%= render 'form' %>

app/views/retrospectives/index.html.erb
<h1 class="ls-title-intro ls-ico-home"><%= t('title.retrospectives') %></h1>

<% if @next_retrospective.present? %>
  <div class="ls-box ls-board-box">
    <header class="ls-info-header">
      <h2 class="ls-title-3"><%= t('title.next_retrospective') %></h2>
    </header>
    <div class="ls-list">
      <header class="ls-list-header">
        <div class="ls-list-title col-md-9">
          <%= link_to @next_retrospective.title, team_retrospective_path(current_team, @next_retrospective) %>
          <small><%= t('table.date') %>: <%= l @next_retrospective.date.to_date, format: :default %> - <%= l @next_retrospective.schedule, format: :small %></small>
        </div>
        <div class="col-md-3 ls-txt-right hidden-xs">
          <%= link_to t('button.view'), team_retrospective_path(current_team, @next_retrospective), class: 'ls-btn-primary' %>
        </div>
      </header>
    </div>
  </div>

  <div class="ls-box ls-board-box">
    <header class="ls-info-header">
      <h2 class="ls-title-3"><%= t('title.retrospectives_historic') %></h2>
    </header>
    <div class="ls-table-responsive">
      <table class="ls-table">
        <thead>
          <tr>
            <th><%= t('table.title') %></th>
            <th><%= t('table.date') %></th>
            <th><%= t('table.schedule') %></th>
            <th><%= t('table.room') %></th>
            <th><%= t('table.actions') %></th>
          </tr>
        </thead>
        <tbody>
          <% @retrospectives.each do |r| %>
            <tr>
              <td><%= link_to r.title, team_retrospective_path(current_team, r) %></td>
              <td><%= l r.date.to_date, format: :default %></td>
              <td><%= l r.schedule, format: :small %></td>
              <td><%= t('table.room') %> <%= r.room %></td>
              <td>
                <div class="ls-group-btn">
                  <%= link_to '', edit_team_retrospective_path(current_team, r.id), class: 'ls-btn ls-ico-pencil' %>
                  <%= link_to '', [current_team, r], class: 'ls-btn-danger ls-ico-close', method: :delete, data: { confirm: t('confirm') } %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% else %>
  <div class="ls-box ls-board-box">
    <header class="ls-info-header">
      <h2 class="ls-title-3"><%= t('title.next_retrospective') %></h2>
    </header>
    <div class="ls-list">
      <header class="ls-list-header">
        <div class="ls-list-title col-md-9">
          <%= link_to 'Você ainda não possui nenhuma retrospectiva criada.', new_team_retrospective_path(current_team), title: t('menu.create_retrospective') %>
          <small>Clique no botão ao lado para criar sua primeira retrospectivs.</small>
        </div>
        <div class="col-md-3 ls-txt-right">
          <%= link_to t('menu.create_retrospective'), new_team_retrospective_path(current_team), class: 'ls-btn-primary', title: t('menu.create_retrospective') %>
        </div>
      </header>
    </div>
  </div>
<% end %>

app/views/retrospectives/new.html.erb
<h1 class="ls-title-intro ls-ico-plus"><%= t('title.new_retrospective') %></h1>

<%= render 'form' %>

app/views/retrospectives/show.html.erb
<h1 class="ls-title-intro ls-ico-week"><%= @retrospective.title %></h1>

<span class="ls-tag-info"><%= t('tag.date') %>: <%= l @retrospective.date.to_date, format: :default %></span>
<span class="ls-tag-info"><%= t('tag.schedule') %>: <%= l @retrospective.schedule, format: :small %></span>
<span class="ls-tag-info"><%= t('tag.room') %>: <%= @retrospective.room %></span>

<!-- Actions -->
<div class="ls-box ls-board-box">
  <header class="ls-info-header">
    <h2 class="ls-title-3"><%= t('title.actions') %></h2>
  </header>
  <%= render partial: 'shared/forms/demand', locals: {
    object: @demand,
    classes: 'ls-form ls-form-horizontal validate'
  } if @is_enabled %>

  <div class="ls-table-responsive">
    <table class="ls-table ls-table-striped" id="demands-table">
      <thead>
        <th><%= t('table.description') %></th>
        <th><%= t('table.user') %></th>
        <th><%= t('table.status') %></th>
        <th><%= t('table.opened_to') %></th>
        <th class="ls-width-150"><%= t('table.actions') %></th>
      </thead>
      <tbody>
        <% @demands.each do |d| %>
          <tr data-demand-id="<%= d.id %>">
            <td class="description"><%= d.description %></td>
            <td class="user"><%= d.user %></td>
            <td>
              <div data-ls-module="switchButton" class="ls-switch-btn">
                <%= check_box_tag '', '1',  d.status %>
                <label class="ls-switch-label" ls-switch-off="<%= t('button.pending') %>" ls-switch-on="<%= t('button.completed') %>"><span></span></label>
              </div>
              <%= link_to '', update_status_team_retrospective_demand_path(current_team.id, @retrospective.id, d.id), remote: true, class: 'ls-display-none' %>
            </td>
            <td class="days">
              <%= !d.status ? d.opened_days.to_s + ' ' + t('table.days') : '--' %>
            </td>
            <td class="actions">
              <div class="ls-group-btn">
                <%= link_to '', edit_team_retrospective_demand_path(current_team, @retrospective.id, d.id), remote: true, class: 'ls-btn ls-ico-pencil', title: t('button.edit') %>
                <%= link_to '', [current_team, @retrospective, d], class: 'ls-btn-danger ls-ico-close', method: :delete, remote: true, title: t('button.delete') %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<!-- Pending Actions -->
<% if @latest_demands.count > 0 %>
  <div class="ls-box ls-board-box">
    <header class="ls-info-header">
      <h2 class="ls-title-3"><%= t('table.pending_actions') %></h2>
    </header>
    <div class="ls-table-responsive">
      <table class="ls-table ls-table-striped" id="pending-demands-table">
        <thead>
          <th><%= t('table.description') %></th>
          <th><%= t('table.user') %></th>
          <th><%= t('table.status') %></th>
          <th><%= t('table.opened_to') %></th>
          <th class="ls-width-150"><%= t('table.actions') %></th>
        </thead>
        <tbody>
          <% @latest_demands.each do |d| %>
            <tr data-demand-id="<%= d.id %>">
              <td><%= d.description %></td>
              <td><%= d.user %></td>
              <td>
                <div data-ls-module="switchButton" class="ls-switch-btn">
                  <%= check_box_tag '', '1',  d.status %>
                  <label class="ls-switch-label" ls-switch-off="<%= t('button.pending') %>" ls-switch-on="<%= t('button.completed') %>"><span></span></label>
                </div>
              <%= link_to '', update_status_team_retrospective_demand_path(current_team.id, @retrospective.id, d.id), remote: true, class: 'ls-display-none' %>
              </td>
              <td>
                <%= d.opened_days %> <%= t('table.days') %>
              </td>
              <td>
                <%= link_to '', [current_team, @retrospective, d], class: 'ls-btn-danger ls-ico-close', method: :delete, remote: true, title: t('button.delete') %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

<!-- Positive Topics -->
<div class="ls-box ls-board-box">
  <header class="ls-info-header">
    <h2 class="ls-title-3"><%= t('title.positive_topics') %></h2>
  </header>
  <%= render partial: 'shared/forms/description', locals: {
    object: @positive_topic,
    classes: 'ls-form ls-form-inline row validate'
  } if @is_enabled %>

  <div class="ls-table-responsive">
    <table class="ls-table ls-table-striped" id="positive-topics-table">
      <thead>
        <th><%= t('table.positive_topic') %></th>
        <th class="ls-width-250"><%= t('table.like') %></th>
        <th class="ls-width-150"><%= t('table.actions') %></th>
      </thead>
      <tbody>
        <% @positive_topics.each do |p| %>
          <tr data-id="<%= p.id %>">
            <td class="description"><%= p.description %></td>
            <td class="like">
              <%= link_to (' (' + p.like.to_s + ')'), like_topic_path(p), method: :post, remote: true, class: 'ls-btn ls-color-success ls-ico-thumbs-up like-button' %>
              <%= link_to (' (' + p.dislike.to_s + ')'), dislike_topic_path(p), method: :post, remote: true, class: 'ls-btn ls-color-danger ls-ico-thumbs-up2 dislike-button' %>
            </td>
            <td class="actions">
              <div class="ls-group-btn">
                <%= link_to '', edit_team_retrospective_positive_topic_path(current_team, @retrospective.id, p.id), remote: true, class: 'ls-btn ls-ico-pencil', title: t('button.edit') %>
                <%= link_to '', [current_team, @retrospective, p], class: 'ls-btn-danger ls-ico-close', method: :delete, remote: true, title: t('button.delete') %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<!-- Negative Topics -->
<div class="ls-box ls-board-box">
  <header class="ls-info-header">
    <h2 class="ls-title-3"><%= t('title.negative_topics') %></h2>
  </header>
  <%= render partial: 'shared/forms/description', locals: {
    object: @negative_topic,
    classes: 'ls-form ls-form-inline row validate'
  } if @is_enabled %>

  <div class="ls-table-responsive">
    <table class="ls-table ls-table-striped" id="negative-topics-table">
      <thead>
        <th><%= t('table.negative_topic') %></th>
        <th class="ls-width-250"><%= t('table.like') %></th>
        <th class="ls-width-150"><%= t('table.actions') %></th>
      </thead>
      <tbody>
        <% @negative_topics.each do |p| %>
          <tr data-id="<%= p.id %>">
            <td class="description"><%= p.description %></td>
            <td class="like">
              <%= link_to (' (' + p.like.to_s + ')'), like_topic_path(p), method: :post, remote: true, class: 'ls-btn ls-color-success ls-ico-thumbs-up like-button' %>
              <%= link_to (' (' + p.dislike.to_s + ')'), dislike_topic_path(p), method: :post, remote: true, class: 'ls-btn ls-color-danger ls-ico-thumbs-up2 dislike-button' %>
            </td>
            <td class="actions">
              <div class="ls-group-btn">
                <%= link_to '', edit_team_retrospective_negative_topic_path(current_team, @retrospective.id, p.id), remote: true, class: 'ls-btn ls-ico-pencil', title: t('button.edit') %>
                <%= link_to '', [current_team, @retrospective, p], class: 'ls-btn-danger ls-ico-close', method: :delete, remote: true, title: t('button.delete') %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<!-- Doubts -->
<div class="ls-box ls-board-box">
  <header class="ls-info-header">
    <h2 class="ls-title-3"><%= t('title.doubts') %></h2>
  </header>
  <%= render partial: 'shared/forms/description', locals: {
    object: @doubt,
    classes: 'ls-form ls-form-inline row validate'
  } if @is_enabled %>

  <div class="ls-table-responsive">
    <table class="ls-table ls-table-striped" id="doubts-table">
      <thead>
        <th><%= t('table.doubt') %></th>
        <th class="ls-width-150"><%= t('table.actions') %></th>
      </thead>
      <tbody>
        <% @doubts.each do |d| %>
          <tr data-id="<%= d.id %>">
            <td class="description"><%= d.description %></td>
            <td class="actions">
              <div class="ls-group-btn">
                <%= link_to '', edit_team_retrospective_doubt_path(current_team, @retrospective.id, d.id), remote: true, class: 'ls-btn ls-ico-pencil', title: t('button.edit') %>
                <%= link_to '', [current_team, @retrospective, d], class: 'ls-btn-danger ls-ico-close', method: :delete, remote: true, title: t('button.delete') %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>